### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by objectiveous** [williewheeler/zkybase#1]
FYI, a fresh fork just resulted in the following build error. Probably due to missing repos in my settings.xml. 

dogen:skybase robevans$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] org.skydingo.skybase
[INFO] Skybase Domain
[INFO] Skybase Service
[INFO] Skybase Client
[INFO] Skybase Maven Plugins
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building org.skydingo.skybase 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Skybase Domain 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ org.skydingo.skybase.domain ---
[WARNING] Using platform encoding (MacRoman actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/robevans/Documents/skybase/domain/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ org.skydingo.skybase.domain ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ org.skydingo.skybase.domain ---
[WARNING] Using platform encoding (MacRoman actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/robevans/Documents/skybase/domain/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ org.skydingo.skybase.domain ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.7.2:test (default-test) @ org.skydingo.skybase.domain ---
[INFO] No tests to run.
[INFO] Surefire report directory: /Users/robevans/Documents/skybase/domain/target/surefire-reports

---
##  T E S T S

There are no tests to run.

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ org.skydingo.skybase.domain ---
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Skybase Service 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for javax.servlet:com.springsource.javax.servlet:jar:2.5.0 is missing, no dependency information available
[WARNING] The POM for javax.servlet:com.springsource.javax.servlet.jsp:jar:2.1.0 is missing, no dependency information available
[WARNING] The POM for javax.servlet:com.springsource.javax.servlet.jsp.jstl:jar:1.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.skydingo.skybase .............................. SUCCESS [0.001s]
[INFO] Skybase Domain .................................... SUCCESS [1.394s]
[INFO] Skybase Service ................................... FAILURE [0.197s]
[INFO] Skybase Client .................................... SKIPPED
[INFO] Skybase Maven Plugins ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.766s
[INFO] Finished at: Thu Dec 22 10:04:51 PST 2011
[INFO] Final Memory: 6M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.skydingo.skybase.service: Could not resolve dependencies for project org.skydingo.skybase:org.skydingo.skybase.service:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: javax.servlet:com.springsource.javax.servlet:jar:2.5.0, javax.servlet:com.springsource.javax.servlet.jsp:jar:2.1.0, javax.servlet:com.springsource.javax.servlet.jsp.jstl:jar:1.2.0: Failure to find javax.servlet:com.springsource.javax.servlet:jar:2.5.0 in http://maven.springframework.org/milestone was cached in the local repository, resolution will not be reattempted until the update interval of spring-release has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.skydingo.skybase.service

**Comment by objectiveous** [comment]
Adding the following seems to help. 

<repository>
    <id>com.springsource.repository.bundles.release</id>
    <name>SpringSource Enterprise Bundle Repository - SpringSource Bundle Releases</name>
    <url>http://repository.springsource.com/maven/bundles/release</url>
</repository>
<repository>
    <id>com.springsource.repository.bundles.external</id>
    <name>SpringSource Enterprise Bundle Repository - External Bundle Releases</name>
    <url>http://repository.springsource.com/maven/bundles/external</url>
</repository>

**Comment by objectiveous** [comment]
And then there's some test errors but I might be able to fix that once I suck the project into eclipse. 

---

##  T E S T S

Running org.skydingo.skybase.web.controller.FarmControllerTests
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.235 sec <<< FAILURE!

Results :

Tests in error: 
  testGetFarmList(org.skydingo.skybase.web.controller.FarmControllerTests)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

**Comment by williewheeler** [comment]
Ah, good catch Rob. The POM is using the SpringSource EBR repos, but probably shouldn't be since they don't seem to be updating it with the latest and greatest. Instead of adding the EBR declarations I'll just change the dependencies to the ones in Maven central.

Also I'll add the properties to the POM that prevent the chirping about platform-specific builds.

I'll take a look at the test too. Thanks!

**Comment by williewheeler** [comment]
OK, the fixes are in:

1) Platform-specific build fix
2) Dependencies now come from Maven central rather than EBR
3) Broken unit test fixed.

Thanks Rob. Let me know if you run into any more issues. As you probably know the project is brand new, so there are lots of stubbed out items in the UI right now, broken links and all that. But it ought to build and start up without errors. :-)

**Comment by objectiveous** [comment]
Cheers!
